[testing] fix test to work with phpunit 3.6
4) JMS\Payment\CoreBundle\Tests\PluginController\PluginControllerTest::testAproveAndDepositPluginThrowsException
InvalidArgumentException: You must not expect the generic exception class.

5) JMS\Payment\CoreBundle\Tests\PluginController\PluginControllerTest::testApprovePluginThrowsException
InvalidArgumentException: You must not expect the generic exception class.